#
# SPDX-License-Identifier: Apache-2.0
#
# (c) Collabora Ltd. 2019
# Author: Andrzej Pietrasiewicz <andrzej.p@collabora.com>
#

BASH_DUMMY=0
LINUX_GVFS=1
WINDOWS_POWER_SHELL=2
HOST=$BASH_DUMMY
DISCONNECT_CONNECT_COUNT=1
STORE_NAME=Card
ADD_REMOVE_COUNT=10
MULTIPLE_ADD_REMOVE_COUNT=5
MULTIPLE_FILES=50
